### ISSUE TITLE
Issue a release + don't bump dev version numbers?

### ISSUE THREAD

**Issue by sunshowers** [zkat/supports-color#16]
Hi! Was wondering if you'd be okay issuing a release of supports-color soon to include the fixes that have gone in since 2.0.0.

Separately, would it be okay not bumping the version to e.g. `2.0.1-alpha.0`? Currently, `[patch.crates-io]` requires the version number to be identical which makes it hard to patch a version in from this repository. Leaving the version number at e.g. 2.0.0 would address this issue and allow workspaces to patch in the version.

**Comment by zkat** [comment]
I think I don't understand. You mean you want me to release a new version with the exact same version number? I don't think I can do that? If you mean the weird prerelease thing, I think that won't happen anymore, it was a quirk of an older version of `cargo-release`.

**Comment by sunshowers** [comment]
> You mean you want me to release a new version with the exact same version number

Ah, no, I just meant releasing 2.0.1 or 2.1.0.

> If you mean the weird prerelease thing, I think that won't happen anymore, it was a quirk of an older version of cargo-release.

Gotcha, thanks!

**Comment by zkat** [comment]
`2.1.0` released and published!
