### ISSUE TITLE
`atty` is potentially unsound, not very alive and should be replaced with `is-terminal`

### ISSUE THREAD

**Issue by pacak** [zkat/supports-color#9]
Some links explaining the problem

- https://github.com/softprops/atty/pull/51
- https://github.com/clap-rs/clap/pull/4249#discussion_r1029107456
- https://github.com/rustsec/advisory-db/issues/1457

I can prepare a pull request if you like

**Comment by zkat** [comment]
thanks for posting this. Could I interest you in putting together a PR for this?

**Comment by pacak** [comment]
Looking. Support for `on_cached` seems a bit tricky.
